create table data_test
(
    id text,
    loan_amnt NUMERIC(10,2),
    funded_amnt text,
    funded_amnt_inv text,
    term text,
    int_rate text,
    installment text,
    grade text,
    sub_grade text,
    emp_length text,
    home_ownership text,
    annual_inc text,
    verification_status text,
    issue_d text,
    loan_status text,
    "desc" text,
    purpose text,
    title text,
    zip_code text,
    addr_state text,
    dti text,
    delinq_2yrs text,
    earliest_cr_line text,
    fico_range_low text,
    fico_range_high text,
    inq_last_6mths text,
    mths_since_last_delinq text,
    mths_since_last_record text,
    open_acc text,
    pub_rec text,
    revol_bal text,
    revol_util text,
    total_acc text,
    initial_list_status text,
    out_prncp text,
    out_prncp_inv text,
    total_pymnt text,
    total_pymnt_inv text,
    total_rec_prncp text,
    total_rec_int text,
    total_rec_late_fee text,
    recoveries text,
    collection_recovery_fee text,
    last_pymnt_d text,
    last_pymnt_amnt text,
    next_pymnt_d text,
    last_credit_pull_d text,
    last_fico_range_high text,
    last_fico_range_low text,
    collections_12_mths_ex_med text,
    mths_since_last_major_derog text,
    policy_code text,
    application_type text
);

alter table data_test owner to fijuser;

